"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Story = exports.Projects = exports.Interactives = exports.Contact = exports.Hero = void 0;
var Hero_tsx_1 = require("./Hero.tsx");
Object.defineProperty(exports, "Hero", { enumerable: true, get: function () { return Hero_tsx_1.Hero; } });
var Contact_tsx_1 = require("./Contact.tsx");
Object.defineProperty(exports, "Contact", { enumerable: true, get: function () { return Contact_tsx_1.Contact; } });
var Interactives_tsx_1 = require("./Interactives.tsx");
Object.defineProperty(exports, "Interactives", { enumerable: true, get: function () { return Interactives_tsx_1.Interactives; } });
var Projects_tsx_1 = require("./Projects.tsx");
Object.defineProperty(exports, "Projects", { enumerable: true, get: function () { return Projects_tsx_1.Projects; } });
var Story_tsx_1 = require("./Story.tsx");
Object.defineProperty(exports, "Story", { enumerable: true, get: function () { return Story_tsx_1.Story; } });
