"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Story = exports.Projects = exports.Interactives = exports.Contact = exports.Hero = void 0;
var Hero_1 = require("@/Hero");
Object.defineProperty(exports, "Hero", { enumerable: true, get: function () { return Hero_1.Hero; } });
var Contact_1 = require("@/Contact");
Object.defineProperty(exports, "Contact", { enumerable: true, get: function () { return Contact_1.Contact; } });
var Interactives_1 = require("@/Interactives");
Object.defineProperty(exports, "Interactives", { enumerable: true, get: function () { return Interactives_1.Interactives; } });
var Projects_1 = require("@/Projects");
Object.defineProperty(exports, "Projects", { enumerable: true, get: function () { return Projects_1.Projects; } });
var Story_1 = require("@/Story");
Object.defineProperty(exports, "Story", { enumerable: true, get: function () { return Story_1.Story; } });
